### ISSUE TITLE
Email sending issue

### ISSUE THREAD

**Issue by aPoluden** [aPoluden/autoreseller#17]
celery-worker_1  | Traceback (most recent call last):
celery-worker_1  |   File "/app/crawler/tasks.py", line 99, in instant_advert_notification_task
celery-worker_1  |     email.send()
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/message.py", line 294, in send
celery-worker_1  |     return self.get_connection(fail_silently).send_messages([self])
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
celery-worker_1  |     new_conn_created = self.open()
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 70, in open
celery-worker_1  |     self.connection.login(self.username, self.password)
celery-worker_1  |   File "/usr/local/lib/python3.6/smtplib.py", line 730, in login
celery-worker_1  |     raise last_exception
celery-worker_1  |   File "/usr/local/lib/python3.6/smtplib.py", line 721, in login
celery-worker_1  |     initial_response_ok=initial_response_ok)
celery-worker_1  |   File "/usr/local/lib/python3.6/smtplib.py", line 642, in auth
celery-worker_1  |     raise SMTPAuthenticationError(code, resp)
celery-worker_1  | smtplib.SMTPAuthenticationError: (534, b'5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvl\n5.7.14 jRJ0AO60AvXa-pQ5tvLQuKyMTGWVf2ZSl0sD-aNC4z7Gbr5wLkl-NsoxSgKTWhI2K14Fhp\n5.7.14 gGQDp-rJTrYZX1kuAN14yvFOSPjb6FyNgruNx40RnP8SHb9N-WqmKmr-n5I6FIoc8L1Qyt\n5.7.14 xZRFU0nth3ZNzc62WulpHAy-Uw8aR_AQgUS9i4mfLs8U8aVGAnCo6-pMF2Z-LZcfjhx53d\n5.7.14 ECjVZZoqwXqhuHGM8q4TjdUPg33zk> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 o101-v6sm6462633wrb.44 - gsmtp')
celery-worker_1  | 
celery-worker_1  | During handling of the above exception, another exception occurred:
celery-worker_1  | 
celery-worker_1  | Traceback (most recent call last):
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
celery-worker_1  |     R = retval = fun(*args, **kwargs)
celery-worker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
celery-worker_1  |     return self.run(*args, **kwargs)
celery-worker_1  |   File "/app/crawler/tasks.py", line 102, in instant_advert_notification_task
celery-worker_1  |     logger.warn('Advert {} processing fail'.format(advert_data['advert']['url']))
celery-worker_1  | TypeError: 'NoneType' object is not subscriptable

**Comment by aPoluden** [comment]
Issue caused google account security policies
